<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SmartWarehouse.Entities\SmartWarehouse.Entities.csproj" />
    <ProjectReference Include="..\SmartWarehouse.DataAccess\SmartWarehouse.DataAccess.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
